name: dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt-hotspot'
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run unit tests
      run: ./gradlew test
    - name: run lint
      run: ./gradlew lint
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.3
      with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
